### ISSUE TITLE
nosetests

### ISSUE THREAD

**Issue by xwa9860** [pyrk/pyrk#20]
nosetests gives 'import error' after you added __init__.py in the main folder. Is there a quick way to fix this? Apparently a not so quick way is to add pyrk. in all the import statements in the test folder.

**Comment by katyhuff** [comment]
Not sure I understand. I added init.py to the main folder 7 months ago. It's been passing on my machine and on travis since then. (note that the appearance of a failing test on travis recently was because I added a tag recently, to the early v0.0 commit. That wasn't a real build it just triggered a new travis build of a very old version of the code (the very first commit). it wasn't new code. the master branch build is represented by build https://travis-ci.org/pyrk/pyrk/builds/77207487 which passes.) Please indicate what branch and version you're running such that the build fails.

Here's the result on my machine:

```
khuff@hypatia:~/repos/pyrk/pyrk(master) $ nosetests
..............................................
----------------------------------------------------------------------
Ran 46 tests in 0.654s

OK
```

Probably you need to make sure that your pythonpath includes the pyrk directory...

**Comment by xwa9860** [comment]
Sorry, false alarm. I messed around and it suddenly works again...
